source_dir: "/vols/cms/ks1021/offline/HiggsDNA/IC/output/production_fixPU/Run3_2022/tt"

destination_dir: "/vols/cms/ia2318/REAL/data/Run3_2022"

source_files:
  data:
    - "Tau_Run2022C"
    - "Tau_Run2022D"
  mc:
    - "DYto2L_M-50_1J_madgraphMLM"
    - "DYto2L_M-50_2J_madgraphMLM"
    - "DYto2L_M-50_3J_madgraphMLM"
    - "DYto2L_M-50_4J_madgraphMLM"
    - "DYto2L_M-50_madgraphMLM"
    - "DYto2L_M-50_madgraphMLM_ext1"
    - "ST_t-channel_antitop_4f_InclusiveDecays"
    - "ST_t-channel_top_4f_InclusiveDecays"
    - "ST_tW_antitop_2L2Nu"
    - "ST_tW_antitop_2L2Nu_ext1"
    - "ST_tW_antitop_LNu2Q"
    - "ST_tW_antitop_LNu2Q_ext1"
    - "ST_tW_top_2L2Nu"
    - "ST_tW_top_2L2Nu_ext1"
    - "ST_tW_top_LNu2Q"
    - "ST_tW_top_LNu2Q_ext1"
    - "TTto2L2Nu"
    - "TTto2L2Nu_ext1"
    - "TTto4Q"
    - "TTto4Q_ext1"
    - "TTtoLNu2Q"
    - "TTtoLNu2Q_ext1"
    - "WtoLNu_1J_madgraphMLM"
    - "WtoLNu_2J_madgraphMLM"
    - "WtoLNu_3J_madgraphMLM"
    - "WtoLNu_4J_madgraphMLM"
    - "WtoLNu_madgraphMLM"
    - "WtoLNu_madgraphMLM_ext1"
    - "WW"
    - "WZ"
    - "ZZ"
  
