source_dir: "/vols/cms/ia2318/HiggsDNA-powheg/output/JanuaryEarlyRun3/Run3_2022EE/{channel}"

destination_dir: "/vols/cms/ia2318/REAL/data_January26/Run3_2022EE/{channel}_{ff_process}"

source_files:
  tt_data:
    - "Tau_Run2022E"
    - "Tau_Run2022F"
    - "Tau_Run2022G"
  mt_data:
    - "Muon_Run2022E"
    - "Muon_Run2022F"
    - "Muon_Run2022G"
  et_data:
    - "EGamma_Run2022E"
    - "EGamma_Run2022F"
    - "EGamma_Run2022G"
  mc:
    - "DYto2L_M_50_amcatnloFXFX"
    - "DYto2L_M_50_amcatnloFXFX_ext1"
    - "DYto2L_M_50_0J_amcatnloFXFX"
    - "DYto2L_M_50_1J_amcatnloFXFX"
    - "DYto2L_M_50_2J_amcatnloFXFX"
    - "DYto2Tau_MLL_50_0J_amcatnloFXFX"
    - "DYto2Tau_MLL_50_1J_amcatnloFXFX"
    - "DYto2Tau_MLL_50_2J_amcatnloFXFX"
    - "ST_t_channel_antitop_4f_InclusiveDecays"
    - "ST_t_channel_top_4f_InclusiveDecays"
    - "ST_tW_antitop_2L2Nu"
    - "ST_tW_antitop_2L2Nu_ext1"
    - "ST_tW_antitop_LNu2Q"
    - "ST_tW_antitop_LNu2Q_ext1"
    - "ST_tW_top_2L2Nu"
    - "ST_tW_top_2L2Nu_ext1"
    - "ST_tW_top_LNu2Q"
    - "ST_tW_top_LNu2Q_ext1"
    - "TTto2L2Nu"
    - "TTto2L2Nu_ext1"
    - "TTtoLNu2Q"
    - "TTtoLNu2Q_ext1"
    - "WtoLNu_1J_madgraphMLM"
    - "WtoLNu_2J_madgraphMLM"
    - "WtoLNu_3J_madgraphMLM"
    - "WtoLNu_4J_madgraphMLM"
    - "WtoLNu_madgraphMLM"
    - "WtoLNu_madgraphMLM_ext1"
    - "WW"
    - "WZ"
    - "ZZ"
  
