BBHto2Tau_M_100:
  eff: 1493830
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1000:
  eff: 346478
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1000_ext1:
  eff: 346478
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_100_ext1:
  eff: 1493830
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_105:
  eff: 1424030
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_105_ext1:
  eff: 1424030
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_110:
  eff: 1395424
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1100:
  eff: 346452
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1100_ext1:
  eff: 346452
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_110_ext1:
  eff: 1395424
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_115:
  eff: 1492431
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_115_ext1:
  eff: 1492431
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_120:
  eff: 1345195
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1200:
  eff: 171438
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1200_ext1:
  eff: 171438
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_120_ext1:
  eff: 1345195
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_125:
  eff: 1478130
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_125_ext1:
  eff: 1478130
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_130:
  eff: 1487050
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_130_ext1:
  eff: 1487050
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_135:
  eff: 1563411
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_135_ext1:
  eff: 1563411
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_140:
  eff: 1455580
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1400:
  eff: 167888
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1400_ext1:
  eff: 167888
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_140_ext1:
  eff: 1455580
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_160:
  eff: 1425584
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1600:
  eff: 161820
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1600_ext1:
  eff: 161820
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_160_ext1:
  eff: 1425584
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_180:
  eff: 1479854
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1800:
  eff: 161342
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_1800_ext1:
  eff: 161342
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_180_ext1:
  eff: 1479854
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_200:
  eff: 1473830
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2000:
  eff: 159926
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2000_ext1:
  eff: 159926
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_200_ext1:
  eff: 1473830
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2300:
  eff: 154404
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2300_ext1:
  eff: 154404
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_250:
  eff: 724504
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_250_ext1:
  eff: 724504
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2600:
  eff: 150978
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2600_ext1:
  eff: 150978
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2900:
  eff: 151298
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_2900_ext1:
  eff: 151298
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_300:
  eff: 724790
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_300_ext1:
  eff: 724790
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_3200:
  eff: 148604
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_3200_ext1:
  eff: 148604
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_350:
  eff: 710264
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_3500:
  eff: 146675
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_3500_ext1:
  eff: 146675
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_350_ext1:
  eff: 710264
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_400:
  eff: 722506
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_400_ext1:
  eff: 722506
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_450:
  eff: 723256
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_450_ext1:
  eff: 723256
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_500:
  eff: 727824
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_500_ext1:
  eff: 727824
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_60:
  eff: 1574356
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_600:
  eff: 363190
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_600_ext1:
  eff: 363190
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_60_ext1:
  eff: 1574356
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_65:
  eff: 1479760
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_65_ext1:
  eff: 1479760
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_70:
  eff: 1467360
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_700:
  eff: 364596
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_700_ext1:
  eff: 364596
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_70_ext1:
  eff: 1467360
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_75:
  eff: 1494236
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_75_ext1:
  eff: 1494236
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_80:
  eff: 1485326
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_800:
  eff: 358033
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_800_ext1:
  eff: 358033
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_80_ext1:
  eff: 1485326
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_85:
  eff: 1489267
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_85_ext1:
  eff: 1489267
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_90:
  eff: 1489138
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_900:
  eff: 348970
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_900_ext1:
  eff: 348970
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_90_ext1:
  eff: 1489138
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_95:
  eff: 1458171
  filter_efficiency: 1.0
  xs: 1.0
BBHto2Tau_M_95_ext1:
  eff: 1458171
  filter_efficiency: 1.0
  xs: 1.0
DYto2L_M_10to50_amcatnloFXFX:
  eff: 168535477
  filter_efficiency: 1.0
  xs: 1327.8
DYto2L_M_10to50_madgraphMLM:
  eff: 520125461
  filter_efficiency: 1.0
  xs: 1091.1
DYto2L_M_50_0J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_1J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_1J_madgraphMLM:
  eff: 494841164
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_2J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_2J_madgraphMLM:
  eff: 494841164
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_3J_madgraphMLM:
  eff: 494841164
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_4J_madgraphMLM:
  eff: 494841164
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_100to200_1J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_100to200_2J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_200to400_1J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_200to400_2J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_400to600_1J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_400to600_2J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_40to100_1J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_40to100_2J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_600_1J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_PTLL_600_2J_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_amcatnloFXFX:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_amcatnloFXFX_ext1:
  eff: 383440237
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_madgraphMLM:
  eff: 494841164
  filter_efficiency: 1.0
  xs: 6282.6
DYto2L_M_50_madgraphMLM_ext1:
  eff: 494841164
  filter_efficiency: 1.0
  xs: 6282.6
GluGluHTo2Tau_UncorrelatedDecay_CPodd_Filtered_ProdAndDecay:
  eff: 21495773
  filter_efficiency: 0.3848
  xs: 3.2759
GluGluHTo2Tau_UncorrelatedDecay_CPodd_UnFiltered_ProdAndDecay:
  eff: 448150
  filter_efficiency: 1.0
  xs: 3.2759
GluGluHTo2Tau_UncorrelatedDecay_MM_Filtered_ProdAndDecay:
  eff: 20689379
  filter_efficiency: 0.3848
  xs: 3.2759
GluGluHTo2Tau_UncorrelatedDecay_MM_UnFiltered_ProdAndDecay:
  eff: 441570
  filter_efficiency: 1.0
  xs: 3.2759
GluGluHTo2Tau_UncorrelatedDecay_SM_Filtered_ProdAndDecay:
  eff: 19599725
  filter_efficiency: 0.3847
  xs: 3.2759
GluGluHTo2Tau_UncorrelatedDecay_SM_UnFiltered_ProdAndDecay:
  eff: 445092
  filter_efficiency: 1.0
  xs: 3.2759
GluGluHto2Tau_M_1000_2HDM_II:
  eff: 1549990
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_100_2HDM_II:
  eff: 1547719
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_105_2HDM_II:
  eff: 1540584
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_1100_2HDM_II:
  eff: 1549992
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_110_2HDM_II:
  eff: 1544176
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_115_2HDM_II:
  eff: 1549860
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_1200_2HDM_II:
  eff: 1549316
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_120_2HDM_II:
  eff: 1547781
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_125_2HDM_II:
  eff: 1547076
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_130_2HDM_II:
  eff: 1544919
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_135_2HDM_II:
  eff: 1549880
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_1400_2HDM_II:
  eff: 1549988
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_140_2HDM_II:
  eff: 1549870
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_1600_2HDM_II:
  eff: 1549325
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_160_2HDM_II:
  eff: 1542876
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_1800_2HDM_II:
  eff: 1549976
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_180_2HDM_II:
  eff: 1545018
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_2000_2HDM_II:
  eff: 1536830
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_200_2HDM_II:
  eff: 1548504
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_2300_2HDM_II:
  eff: 1546721
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_250_2HDM_II:
  eff: 1549952
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_2600_2HDM_II:
  eff: 1545307
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_2900_2HDM_II:
  eff: 1544245
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_300_2HDM_II:
  eff: 1546483
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_3200_2HDM_II:
  eff: 1540846
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_3500_2HDM_II:
  eff: 1549103
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_350_2HDM_II:
  eff: 1545112
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_400_2HDM_II:
  eff: 1542280
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_450_2HDM_II:
  eff: 1543046
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_500_2HDM_II:
  eff: 1549968
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_600_2HDM_II:
  eff: 1542452
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_60_2HDM_II:
  eff: 1548280
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_65_2HDM_II:
  eff: 1538378
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_700_2HDM_II:
  eff: 1540296
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_70_2HDM_II:
  eff: 1549752
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_75_2HDM_II:
  eff: 1544788
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_800_2HDM_II:
  eff: 1545880
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_80_2HDM_II:
  eff: 1540563
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_85_2HDM_II:
  eff: 1541992
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_900_2HDM_II:
  eff: 1543092
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_90_2HDM_II:
  eff: 1549802
  filter_efficiency: 1.0
  xs: 1.0
GluGluHto2Tau_M_95_2HDM_II:
  eff: 1546280
  filter_efficiency: 1.0
  xs: 1.0
ST_tW_antitop_2L2Nu:
  eff: 16782203
  filter_efficiency: 1.0
  xs: 3.8
ST_tW_antitop_2L2Nu_ext1:
  eff: 16782203
  filter_efficiency: 1.0
  xs: 3.8
ST_tW_antitop_4Q:
  eff: 25974756
  filter_efficiency: 1.0
  xs: 3.9
ST_tW_antitop_4Q_ext1:
  eff: 25974756
  filter_efficiency: 1.0
  xs: 3.9
ST_tW_antitop_LNu2Q:
  eff: 33757009
  filter_efficiency: 1.0
  xs: 15.9
ST_tW_antitop_LNu2Q_ext1:
  eff: 33757009
  filter_efficiency: 1.0
  xs: 15.9
ST_tW_top_2L2Nu:
  eff: 16575338
  filter_efficiency: 1.0
  xs: 3.8
ST_tW_top_2L2Nu_ext1:
  eff: 16575338
  filter_efficiency: 1.0
  xs: 3.8
ST_tW_top_4Q:
  eff: 27459158
  filter_efficiency: 1.0
  xs: 3.9
ST_tW_top_4Q_ext1:
  eff: 27459158
  filter_efficiency: 1.0
  xs: 3.9
ST_tW_top_LNu2Q:
  eff: 32511808
  filter_efficiency: 1.0
  xs: 15.8
ST_tW_top_LNu2Q_ext1:
  eff: 32511808
  filter_efficiency: 1.0
  xs: 15.8
ST_t_channel_antitop_4f_InclusiveDecays:
  eff: 4794814
  filter_efficiency: 1.0
  xs: 75.47
ST_t_channel_top_4f_InclusiveDecays:
  eff: 9368799
  filter_efficiency: 1.0
  xs: 123.8
TTto2L2Nu:
  eff: 167682796
  filter_efficiency: 1.0
  xs: 98.04387875606875
TTto2L2Nu_ext1:
  eff: 167682796
  filter_efficiency: 1.0
  xs: 98.04387875606875
TTto4Q:
  eff: 363409416
  filter_efficiency: 1.0
  xs: 419.8071644141188
TTto4Q_ext1:
  eff: 363409416
  filter_efficiency: 1.0
  xs: 419.8071644141188
TTtoLNu2Q:
  eff: 537883189
  filter_efficiency: 1.0
  xs: 405.74895682981236
TTtoLNu2Q_ext1:
  eff: 537883189
  filter_efficiency: 1.0
  xs: 405.74895682981236
VBFHToTauTau_UncorrelatedDecay_Filtered:
  eff: 14552639
  filter_efficiency: 0.4091
  xs: 0.2558
VBFHToTauTau_UncorrelatedDecay_UnFiltered:
  eff: 396754
  filter_efficiency: 1.0
  xs: 0.2558
WW:
  eff: 53112080
  filter_efficiency: 1.0
  xs: 122.27052
WZ:
  eff: 26722782
  filter_efficiency: 1.0
  xs: 41.1474
WminusHToTauTau_UncorrelatedDecay_Filtered:
  eff: 1480135
  filter_efficiency: 0.3944
  xs: 0.03561
WminusHToTauTau_UncorrelatedDecay_UnFiltered:
  eff: 63910
  filter_efficiency: 1.0
  xs: 0.03561
WplusHToTauTau_UncorrelatedDecay_Filtered:
  eff: 2025321
  filter_efficiency: 0.3743
  xs: 0.05575
WplusHToTauTau_UncorrelatedDecay_UnFiltered:
  eff: 66154
  filter_efficiency: 1.0
  xs: 0.05575
WtoLNu_1J_madgraphMLM:
  eff: 683448011
  filter_efficiency: 1.0
  xs: 63425.09999999999
WtoLNu_2J_madgraphMLM:
  eff: 683448011
  filter_efficiency: 1.0
  xs: 63425.09999999999
WtoLNu_3J_madgraphMLM:
  eff: 683448011
  filter_efficiency: 1.0
  xs: 63425.09999999999
WtoLNu_4J_madgraphMLM:
  eff: 683448011
  filter_efficiency: 1.0
  xs: 63425.09999999999
WtoLNu_madgraphMLM:
  eff: 683448011
  filter_efficiency: 1.0
  xs: 63425.09999999999
WtoLNu_madgraphMLM_ext1:
  eff: 683448011
  filter_efficiency: 1.0
  xs: 63425.09999999999
ZHToTauTau_UncorrelatedDecay_Filtered:
  eff: 1863291
  filter_efficiency: 0.3933
  xs: 0.0592
ZHToTauTau_UncorrelatedDecay_UnFiltered:
  eff: 69650
  filter_efficiency: 1.0
  xs: 0.0592
ZZ:
  eff: 4043040
  filter_efficiency: 1.0
  xs: 19.431
lumi: 26671.7
