source_dir: "/vols/cms/ia2318/HiggsDNA/output/production_070525_EarlyRun3SyncMSSM/Run3_2023/{channel}"

destination_dir: "/vols/cms/ia2318/REAL/data_production_071025/Run3_2023/{channel}_{ff_process}"

source_files:
  tt_data:
    - "Tau_Run2023C_v1"
    - "Tau_Run2023C_v2"
    - "Tau_Run2023C_v3"
    - "Tau_Run2023C_v4"
  mt_data:
    - "Muon0_Run2023C_v1"
    - "Muon0_Run2023C_v2"
    - "Muon0_Run2023C_v3"
    - "Muon0_Run2023C_v4"
    - "Muon1_Run2023C_v1"
    - "Muon1_Run2023C_v2"
    - "Muon1_Run2023C_v3"
    - "Muon1_Run2023C_v4"
  et_data:
    - "EGamma0_Run2023C_v1"
    - "EGamma0_Run2023C_v2"
    - "EGamma0_Run2023C_v3"
    - "EGamma0_Run2023C_v4"
    - "EGamma1_Run2023C_v1"
    - "EGamma1_Run2023C_v2"
    - "EGamma1_Run2023C_v3"
    - "EGamma1_Run2023C_v4"
  mc:
    - "DYto2L_M_10to50_madgraphMLM"
    - "DYto2L_M_50_1J_madgraphMLM"
    - "DYto2L_M_50_2J_madgraphMLM"
    - "DYto2L_M_50_3J_madgraphMLM"
    - "DYto2L_M_50_4J_madgraphMLM"
    - "DYto2L_M_50_madgraphMLM"
    - "ST_t_channel_antitop_4f_InclusiveDecays"
    - "ST_t_channel_top_4f_InclusiveDecays"
    - "ST_tW_antitop_2L2Nu"
    - "ST_tW_antitop_4Q"
    # - "ST_tW_antitop_LNu2Q" hashed in pre-processing/samples.yaml
    - "ST_tW_top_2L2Nu"
    - "ST_tW_top_4Q"
    - "ST_tW_top_LNu2Q"
    - "TTto2L2Nu"
    - "TTto4Q"
    - "TTtoLNu2Q"
    - "WtoLNu_1J_madgraphMLM"
    - "WtoLNu_2J_madgraphMLM"
    - "WtoLNu_3J_madgraphMLM"
    - "WtoLNu_4J_madgraphMLM"
    - "WtoLNu_madgraphMLM"
    - "WW"
    - "WZ"
    - "ZZ"
  
